export const fields = {
  username: {
    label: "Name",
    name: "username",
    type: "text",
    placeholder: "Name",
    title: "*The Name field must be more than 2 and less than 15 characters",
    required: true,
  },
  surname: {
    label: "Surname",
    name: "surname",
    type: "text",
    placeholder: "Surname",
    title: "*The Surname field must be more than 2 and less than 50 characters",
    required: false,
  },
  email: {
    label: "Email",
    name: "email",
    type: "text",
    placeholder: "Email",
    title: "*Enter a valid email",
    required: true,
  },
  password: {
    label: "Password",
    name: "password",
    type: "password",
    placeholder: "Password",
    title:
      "*The Password field must be more than 2 and less than 21 characters",
    required: true,
  },
  city: {
    label: "City",
    name: "city",
    type: "text",
    placeholder: "City",
    title: "*The City field must be more than 2 and less than 50 characters",
    required: false,
  },
  address: {
    label: "Address",
    name: "address",
    type: "text",
    placeholder: "Address",
    title: "*The Address field must be more than 2 and less than 50 characters",
    required: false,
  },
  phone: {
    label: "Phone number",
    name: "phone",
    type: "tel",
    placeholder: "Phone number",
    title: "*Enter a valid phone number",
    required: false,
  },
  search: {
    name: "search",
    type: "text",
    title: "",
    required: false,
  },
  keyword: {
    name: "keyword",
    type: "text",
    title: "",
    required: false,
  },
};
